;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html



; !!!! During platformio.ini debugging, not sure whether the settings are correct
; !!!! During platformio.ini debugging, not sure whether the settings are correct
; !!!! During platformio.ini debugging, not sure whether the settings are correct



[platformio]

boards_dir = boards


; select the correct receiver or transmitter
;default_envs = receiver
;src_dir = EoRA-S3-900TB_FreeRTOS_Receiver

default_envs = transmitter
src_dir = EoRA-S3-900TB_FreeRTOS_Transmitter


[env]
platform = espressif32 @ 6.13.0
framework = arduino
board = EoRa_PI_V1
build_flags = 
    -DARDUINO_USB_MODE=1
    ; -DARDUINO_USB_CDC_ON_BOOT=1
    -UARDUINO_USB_CDC_ON_BOOT
    -UARDUINO_USB_DFU_ON_BOOT
    -UARDUINO_USB_MSC_ON_BOOT
    -DCORE_DEBUG_LEVEL=0
    -DUSING_SX1268_433M

;[esp32s3]



[env:receiver]
lib_deps =  jgromes/RadioLib @ 7.5.0
build_flags = ${env.build_flags}



[env:transmitter]
lib_deps =  jgromes/RadioLib @ 7.5.0
            https://github.com/me-no-dev/ESPAsyncWebServer
build_flags = ${env.build_flags}
 


